// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4wJJRNcbDweHqMlEItrLsCSXjZ3MCqzg',
    appId: '1:947096917073:web:1f13da9c221f06de225470',
    messagingSenderId: '947096917073',
    projectId: 'football-de7bd',
    authDomain: 'football-de7bd.firebaseapp.com',
    databaseURL: 'https://football-de7bd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'football-de7bd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1Qb0XE_mF031sQJXshs4cauzfvWSl5hw',
    appId: '1:947096917073:android:f3019a14ca13dd14225470',
    messagingSenderId: '947096917073',
    projectId: 'football-de7bd',
    databaseURL: 'https://football-de7bd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'football-de7bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy6dPxHCv_zJe-0X0j9rOeiQml1X9bhV4',
    appId: '1:947096917073:ios:8fc7fd7bc4e6616e225470',
    messagingSenderId: '947096917073',
    projectId: 'football-de7bd',
    databaseURL: 'https://football-de7bd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'football-de7bd.appspot.com',
    iosClientId: '947096917073-u4te18a2oq2t7k0kv9hbqpvriq8dgv0l.apps.googleusercontent.com',
    iosBundleId: 'com.example.nedeFetyen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy6dPxHCv_zJe-0X0j9rOeiQml1X9bhV4',
    appId: '1:947096917073:ios:8fc7fd7bc4e6616e225470',
    messagingSenderId: '947096917073',
    projectId: 'football-de7bd',
    databaseURL: 'https://football-de7bd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'football-de7bd.appspot.com',
    iosClientId: '947096917073-u4te18a2oq2t7k0kv9hbqpvriq8dgv0l.apps.googleusercontent.com',
    iosBundleId: 'com.example.nedeFetyen',
  );
}
